import React from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { Book, Cpu, BarChart3, Code, GitBranch, Zap } from 'lucide-react';

const Documentation = ({ language = 'zh' }) => {
  return (
    <motion.div
      initial={{ opacity: 0 }}
      animate={{ opacity: 1 }}
      transition={{ duration: 1 }}
      className="max-w-4xl mx-auto px-6 py-12"
    >
      <div className="glass-card p-8 rounded-2xl">
        <div className="flex items-center gap-3 mb-8">
          <div className="w-12 h-12 bg-primary/20 rounded-lg flex items-center justify-center">
            <Book className="text-primary w-6 h-6" />
          </div>
          <h1 className="text-3xl font-bold text-white">AI Image Detector (Multi-Branch ResNet18)</h1>
        </div>

        <div className="prose prose-invert max-w-none">
          <AnimatePresence mode="wait">
            <motion.p 
              key={`${language}-intro1`}
              initial={{ opacity: 0, y: 10 }}
              animate={{ opacity: 1, y: 0 }}
              exit={{ opacity: 0, y: -10 }}
              transition={{ duration: 0.3 }}
              className="text-gray-300 leading-relaxed mb-8 min-h-[80px]"
            >
              {language === 'zh' ? '基于多分支架构（RGB + 噪声 + 频域）的 AI 生成图像检测系统。本项目旨在通过融合多模态特征，高精度识别由 AIGC（AI Generated Content）模型生成的伪造图像。' : 'AI-generated image detection system based on multi-branch architecture (RGB + Noise + Frequency). This project aims to accurately identify fake images generated by AIGC (AI Generated Content) models through fusing multi-modal features.'}
            </motion.p>
          </AnimatePresence>

          <AnimatePresence mode="wait">
            <motion.p 
              key={`${language}-intro2`}
              initial={{ opacity: 0, y: 10 }}
              animate={{ opacity: 1, y: 0 }}
              exit={{ opacity: 0, y: -10 }}
              transition={{ duration: 0.3 }}
              className="text-gray-300 leading-relaxed mb-8 min-h-[40px]"
            >
              {language === 'zh' ? '当前版本采用 <strong className="text-primary">ResNet18</strong> 作为核心骨干网络，并在 <strong className="text-primary">CIFAKE</strong> 与 <strong className="text-primary">Artifact</strong> 混合数据集上取得了优异性能。' : 'The current version uses <strong className="text-primary">ResNet18</strong> as the core backbone network and has achieved excellent performance on the mixed dataset of <strong className="text-primary">CIFAKE</strong> and <strong className="text-primary">Artifact</strong>.'}
            </motion.p>
          </AnimatePresence>

          <AnimatePresence mode="wait">
            <motion.h2 
              key={`${language}-performance`}
              initial={{ opacity: 0, x: -10 }}
              animate={{ opacity: 1, x: 0 }}
              exit={{ opacity: 0, x: 10 }}
              transition={{ duration: 0.3 }}
              className="text-2xl font-bold text-white mb-4 flex items-center gap-2"
            >
              <BarChart3 className="text-secondary w-5 h-5" />
              {language === 'zh' ? '核心性能' : 'Core Performance'}
            </motion.h2>
          </AnimatePresence>

          <div className="glass p-6 rounded-xl mb-8">
            <AnimatePresence mode="wait">
              <motion.p 
                key={`${language}-test-results`}
                initial={{ opacity: 0 }}
                animate={{ opacity: 1 }}
                exit={{ opacity: 0 }}
                transition={{ duration: 0.3 }}
                className="text-gray-400 mb-4"
              >
                {language === 'zh' ? '在混合数据集（CIFAKE + Artifact）上的测试结果（Epoch 10）：' : 'Test results on mixed dataset (CIFAKE + Artifact) (Epoch 10):'}
              </motion.p>
            </AnimatePresence>
            <ul className="space-y-3">
              <AnimatePresence mode="wait">
                <motion.li 
                  key={`${language}-accuracy`}
                  initial={{ opacity: 0, y: 5 }}
                  animate={{ opacity: 1, y: 0 }}
                  exit={{ opacity: 0, y: -5 }}
                  transition={{ duration: 0.3 }}
                  className="flex items-center gap-3"
                >
                  <div className="w-2 h-2 bg-primary rounded-full"></div>
                  <span className="text-white"><strong>{language === 'zh' ? '准确率 (Accuracy):' : 'Accuracy:'}</strong> <span className="text-primary font-bold">87.31%</span></span>
                </motion.li>
              </AnimatePresence>
              <AnimatePresence mode="wait">
                <motion.li 
                  key={`${language}-auc`}
                  initial={{ opacity: 0, y: 5 }}
                  animate={{ opacity: 1, y: 0 }}
                  exit={{ opacity: 0, y: -5 }}
                  transition={{ duration: 0.3, delay: 0.1 }}
                  className="flex items-center gap-3"
                >
                  <div className="w-2 h-2 bg-primary rounded-full"></div>
                  <span className="text-white"><strong>AUC (Area Under Curve):</strong> <span className="text-primary font-bold">0.9496</span></span>
                </motion.li>
              </AnimatePresence>
              <AnimatePresence mode="wait">
                <motion.li 
                  key={`${language}-speed`}
                  initial={{ opacity: 0, y: 5 }}
                  animate={{ opacity: 1, y: 0 }}
                  exit={{ opacity: 0, y: -5 }}
                  transition={{ duration: 0.3, delay: 0.2 }}
                  className="flex items-center gap-3"
                >
                  <div className="w-2 h-2 bg-primary rounded-full"></div>
                  <span className="text-white"><strong>{language === 'zh' ? '训练速度:' : 'Training Speed:'}</strong> <span className="text-primary font-bold">~930 img/s</span> (RTX 5090)</span>
                </motion.li>
              </AnimatePresence>
            </ul>
          </div>

          <AnimatePresence mode="wait">
            <motion.h2 
              key={`${language}-architecture`}
              initial={{ opacity: 0, x: -10 }}
              animate={{ opacity: 1, x: 0 }}
              exit={{ opacity: 0, x: 10 }}
              transition={{ duration: 0.3 }}
              className="text-2xl font-bold text-white mb-4 flex items-center gap-2"
            >
              <Cpu className="text-secondary w-5 h-5" />
              {language === 'zh' ? '算法架构' : 'Algorithm Architecture'}
            </motion.h2>
          </AnimatePresence>

          <AnimatePresence mode="wait">
            <motion.p 
              key={`${language}-architecture-desc`}
              initial={{ opacity: 0, y: 10 }}
              animate={{ opacity: 1, y: 0 }}
              exit={{ opacity: 0, y: -10 }}
              transition={{ duration: 0.3 }}
              className="text-gray-300 leading-relaxed mb-6 min-h-[40px]"
            >
              {language === 'zh' ? '本项目采用 <strong className="text-primary">Multi-Branch Detector</strong> 架构，支持以下特征分支的灵活组合：' : 'This project adopts the <strong className="text-primary">Multi-Branch Detector</strong> architecture, supporting flexible combination of the following feature branches:'}
            </motion.p>
          </AnimatePresence>

          <div className="space-y-6 mb-8">
            <div className="glass p-6 rounded-xl border border-primary/20">
              <AnimatePresence mode="wait">
                <motion.h3 
                  key={`${language}-rgb-branch`}
                  initial={{ opacity: 0, y: 5 }}
                  animate={{ opacity: 1, y: 0 }}
                  exit={{ opacity: 0, y: -5 }}
                  transition={{ duration: 0.3 }}
                  className="text-xl font-semibold text-white mb-3 flex items-center gap-2"
                >
                  <GitBranch className="text-primary w-5 h-5" />
                  {language === 'zh' ? 'RGB 分支 (主分支)' : 'RGB Branch (Main Branch)'}
                </motion.h3>
              </AnimatePresence>
              <ul className="space-y-2 text-gray-300">
                <AnimatePresence mode="wait">
                  <motion.li 
                    key={`${language}-rgb-backbone`}
                    initial={{ opacity: 0, x: 10 }}
                    animate={{ opacity: 1, x: 0 }}
                    exit={{ opacity: 0, x: -10 }}
                    transition={{ duration: 0.3 }}
                    className="flex items-start gap-2"
                  >
                    <span className="text-primary font-mono text-sm mt-1">•</span>
                    <span><strong>Backbone:</strong> ResNet18 (Pre-trained)</span>
                  </motion.li>
                </AnimatePresence>
                <AnimatePresence mode="wait">
                  <motion.li 
                    key={`${language}-rgb-function`}
                    initial={{ opacity: 0, x: 10 }}
                    animate={{ opacity: 1, x: 0 }}
                    exit={{ opacity: 0, x: -10 }}
                    transition={{ duration: 0.3, delay: 0.1 }}
                    className="flex items-start gap-2"
                  >
                    <span className="text-primary font-mono text-sm mt-1">•</span>
                    <span><strong>{language === 'zh' ? '作用:' : 'Function:'}</strong> {language === 'zh' ? '提取图像的高层语义特征和纹理细节。' : 'Extract high-level semantic features and texture details of images.'}</span>
                  </motion.li>
                </AnimatePresence>
                <AnimatePresence mode="wait">
                  <motion.li 
                    key={`${language}-rgb-config`}
                    initial={{ opacity: 0, x: 10 }}
                    animate={{ opacity: 1, x: 0 }}
                    exit={{ opacity: 0, x: -10 }}
                    transition={{ duration: 0.3, delay: 0.2 }}
                    className="flex items-start gap-2"
                  >
                    <span className="text-primary font-mono text-sm mt-1">•</span>
                    <span><strong>{language === 'zh' ? '配置:' : 'Configuration:'}</strong> {language === 'zh' ? '默认启用' : 'Enabled by default'} (<code className="bg-white/5 px-2 py-1 rounded text-xs text-secondary">rgb_pretrained=True</code>)。</span>
                  </motion.li>
                </AnimatePresence>
              </ul>
            </div>

            <div className="glass p-6 rounded-xl border border-secondary/20">
              <AnimatePresence mode="wait">
                <motion.h3 
                  key={`${language}-noise-branch`}
                  initial={{ opacity: 0, y: 5 }}
                  animate={{ opacity: 1, y: 0 }}
                  exit={{ opacity: 0, y: -5 }}
                  transition={{ duration: 0.3 }}
                  className="text-xl font-semibold text-white mb-3 flex items-center gap-2"
                >
                  <Zap className="text-secondary w-5 h-5" />
                  {language === 'zh' ? '噪声分支 (Noise Branch)' : 'Noise Branch'}
                </motion.h3>
              </AnimatePresence>
              <ul className="space-y-2 text-gray-300">
                <AnimatePresence mode="wait">
                  <motion.li 
                    key={`${language}-noise-function`}
                    initial={{ opacity: 0, x: 10 }}
                    animate={{ opacity: 1, x: 0 }}
                    exit={{ opacity: 0, x: -10 }}
                    transition={{ duration: 0.3 }}
                    className="flex items-start gap-2"
                  >
                    <span className="text-secondary font-mono text-sm mt-1">•</span>
                    <span><strong>{language === 'zh' ? '作用:' : 'Function:'}</strong> {language === 'zh' ? '通过隐写分析滤波器（SRM/Bayar）提取图像的噪声残差，捕捉生成模型留下的指纹痕迹。' : 'Extract noise residuals of images through steganalysis filters (SRM/Bayar) to capture fingerprint traces left by generative models.'}</span>
                  </motion.li>
                </AnimatePresence>
                <AnimatePresence mode="wait">
                  <motion.li 
                    key={`${language}-noise-status`}
                    initial={{ opacity: 0, x: 10 }}
                    animate={{ opacity: 1, x: 0 }}
                    exit={{ opacity: 0, x: -10 }}
                    transition={{ duration: 0.3, delay: 0.1 }}
                    className="flex items-start gap-2"
                  >
                    <span className="text-secondary font-mono text-sm mt-1">•</span>
                    <span><strong>{language === 'zh' ? '状态:' : 'Status:'}</strong> {language === 'zh' ? '可选开启。' : 'Optional to enable.'}</span>
                  </motion.li>
                </AnimatePresence>
              </ul>
            </div>

            <div className="glass p-6 rounded-xl border border-accent/20">
              <AnimatePresence mode="wait">
                <motion.h3 
                  key={`${language}-frequency-branch`}
                  initial={{ opacity: 0, y: 5 }}
                  animate={{ opacity: 1, y: 0 }}
                  exit={{ opacity: 0, y: -5 }}
                  transition={{ duration: 0.3 }}
                  className="text-xl font-semibold text-white mb-3 flex items-center gap-2"
                >
                  <Code className="text-accent w-5 h-5" />
                  {language === 'zh' ? '频域分支 (Frequency Branch)' : 'Frequency Branch'}
                </motion.h3>
              </AnimatePresence>
              <ul className="space-y-2 text-gray-300">
                <AnimatePresence mode="wait">
                  <motion.li 
                    key={`${language}-frequency-function`}
                    initial={{ opacity: 0, x: 10 }}
                    animate={{ opacity: 1, x: 0 }}
                    exit={{ opacity: 0, x: -10 }}
                    transition={{ duration: 0.3 }}
                    className="flex items-start gap-2"
                  >
                    <span className="text-accent font-mono text-sm mt-1">•</span>
                    <span><strong>{language === 'zh' ? '作用:' : 'Function:'}</strong> {language === 'zh' ? '利用 DCT/FFT 变换分析图像在频域上的异常分布（如棋盘格效应）。' : 'Use DCT/FFT transform to analyze abnormal distribution in the frequency domain (such as chessboard effect).'}</span>
                  </motion.li>
                </AnimatePresence>
                <AnimatePresence mode="wait">
                  <motion.li 
                    key={`${language}-frequency-status`}
                    initial={{ opacity: 0, x: 10 }}
                    animate={{ opacity: 1, x: 0 }}
                    exit={{ opacity: 0, x: -10 }}
                    transition={{ duration: 0.3, delay: 0.1 }}
                    className="flex items-start gap-2"
                  >
                    <span className="text-accent font-mono text-sm mt-1">•</span>
                    <span><strong>{language === 'zh' ? '状态:' : 'Status:'}</strong> {language === 'zh' ? '可选开启。' : 'Optional to enable.'}</span>
                  </motion.li>
                </AnimatePresence>
              </ul>
            </div>
          </div>

          <div className="glass p-6 rounded-xl mb-8">
            <AnimatePresence mode="wait">
              <motion.h3 
                key={`${language}-fusion`}
                initial={{ opacity: 0, y: 5 }}
                animate={{ opacity: 1, y: 0 }}
                exit={{ opacity: 0, y: -5 }}
                transition={{ duration: 0.3 }}
                className="text-xl font-semibold text-white mb-3"
              >
                {language === 'zh' ? '融合策略' : 'Fusion Strategy'}
              </motion.h3>
            </AnimatePresence>
            <AnimatePresence mode="wait">
              <motion.p 
                key={`${language}-fusion-desc`}
                initial={{ opacity: 0, y: 10 }}
                animate={{ opacity: 1, y: 0 }}
                exit={{ opacity: 0, y: -10 }}
                transition={{ duration: 0.3 }}
                className="text-gray-300 min-h-[60px]"
              >
                {language === 'zh' ? '各分支特征经过提取后，在全连接层前进行拼接 (Concatenation)，并通过 MLP 进行最终分类。这种融合方式能够充分利用不同模态的互补信息，提高检测精度。' : 'After feature extraction from each branch, they are concatenated before the fully connected layer and finally classified through MLP. This fusion method can fully utilize complementary information from different modalities to improve detection accuracy.'}
              </motion.p>
            </AnimatePresence>
          </div>

          <div className="border-t border-white/10 pt-8 mt-8">
            <p className="text-gray-500 text-sm text-center">
              © 2026 AI Forensic Research Lab. All rights reserved.
            </p>
          </div>
        </div>
      </div>
    </motion.div>
  );
};

export default Documentation;